//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public int idAREA { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public int Extension { get; set; }
    
        public virtual ICollection<PERSONA> PERSONA { get; set; }
    }
}
