//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO
    {
        public CARGO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int idCARGO { get; set; }
        public string NombreCargo { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
