//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPOINGRESO
    {
        public int idEQUIPOINGRESO { get; set; }
        public System.DateTime FechaHoraIngreso { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public int idINGRESO { get; set; }
        public int idEQUIPO { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
