//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO
    {
        public INGRESO()
        {
            this.EQUIPOINGRESO = new HashSet<EQUIPOINGRESO>();
        }
    
        public int idINGRESO { get; set; }
        public System.DateTime FechaHoraIngreso { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public int idAREA { get; set; }
        public int idPERSONA { get; set; }
    
        public virtual ICollection<EQUIPOINGRESO> EQUIPOINGRESO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
