//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.INGRESO = new HashSet<INGRESO>();
        }
    
        public int idPERSONA { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Documento { get; set; }
        public int idTIPO { get; set; }
        public int IdAREA { get; set; }
        public int idUSUARIO { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual ICollection<INGRESO> INGRESO { get; set; }
        public virtual TIPO TIPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
