//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO
    {
        public TIPO()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public int idTIPO { get; set; }
        public string NombreTipo { get; set; }
    
        public virtual ICollection<PERSONA> PERSONA { get; set; }
    }
}
