//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityKeyDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public int idUSUARIO { get; set; }
        public string NombreUsuario { get; set; }
        public string Password { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int idCARGO { get; set; }
        public int idROL { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual ICollection<PERSONA> PERSONA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
